# Copyright (C) 2018 Krishna Moniz

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
version: '3.5'

networks:
  network1:
    name: network1

services:
  redis:
    image: redis:5-alpine3.8
    networks:
      - network1

  worker:
    image: certificate-authority_worker:latest
    # build: ./builds/celery
    volumes:
        - ./api:/srv/www/certificate_authority/site
        - ./builds/web:/srv/www/certificate_authority/config/custom
    environment:
        - CONFIG_FILE=/srv/www/certificate_authority/config/custom/config.ini
    command: celery worker -A internal_api.async_api --loglevel=info
    networks:
      - network1
    depends_on:
      - redis

  api:
    restart: always
    # build: ./builds/web
    image: certificate-authority_web:latest
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - CONFIG_FILE=/srv/www/certificate_authority/config/custom/config.ini
      - CONFIG_SECTION=web
    volumes:
      - ./api:/srv/www/certificate_authority/site
      - ./builds/web:/srv/www/certificate_authority/config/custom
    expose:
      - "8000"
    # command: gunicorn -b :8000 --access-logfile - --error-logfile - app:app
    command: flask run --host=0.0.0.0 --port 8000
    networks:
      - network1
    depends_on:
      - redis

  web:
    restart: always
    # build: ./builds/web
    image: certificate-authority_web:latest
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - CONFIG_FILE=/srv/www/certificate_authority/config/custom/config.ini
      - CONFIG_SECTION=web
    volumes:
      - ./web:/srv/www/certificate_authority/site
      - ./builds/web:/srv/www/certificate_authority/config/custom
    expose:
      - "8000"
    # command: gunicorn -b :8000 --access-logfile - --error-logfile - app:app
    command: flask run --host=0.0.0.0 --port 8000
    networks:
      - network1
    depends_on:
      - redis

  ca:
    restart: always
    image: certificate-authority_ca:latest
    # build: ./builds/ca
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - CONFIG_FILE=/srv/www/certificate_authority/config/custom/config.ini
      - CONFIG_SECTION=ca
    volumes:
      - ./ca:/srv/www/certificate_authority/site
      - ./builds/web:/srv/www/certificate_authority/config/custom
    expose:
      - "8000"
    command: flask run --host=0.0.0.0 --port 8000
    networks:
      - network1
    depends_on:
      - redis

  dienst:
    restart: always
    image: certificate-authority_web:latest
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - CONFIG_FILE=/srv/www/certificate_authority/config/custom/config.ini
    volumes:
      - ./dienst:/srv/www/certificate_authority/site
      - ./builds/web:/srv/www/certificate_authority/config/custom
    ports:
      - "8000"
    # command: gunicorn -b :8000 --access-logfile - --error-logfile - app:app
    command: flask run --host=0.0.0.0 --port 8000
    networks:
      - network1
    depends_on:
      - redis

  nginx:
    image: certificate-authority_nginx:latest
    restart: always
    # build: ./builds/nginx
    ports:
      # - "80:80"
      # - "443:443"
      - "8080:8080"
    volumes:
      - ./nginx/web_crt:/srv/www/certificate_authority/ssl/web
      - ./nginx/api_crt:/srv/www/certificate_authority/ssl/api
      - ./nginx/root_ca:/srv/www/certificate_authority/ssl/client
      - ./web/app/static:/srv/www/certificate_authority/site/web/static
      - ./api/app/static:/srv/www/certificate_authority/site/api/static
    networks:
      - network1
    depends_on:
      # - web
      - dienst
